# Add 'documentation' label to any changes within 'docs' folder or any subfolders
documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'README.md'
    - '**/README.md'

# Add 'pkg1' label to any change to pkg1 package.
pkg1:
- all:
  - changed-files:
    - any-glob-to-any-file: 'pkg1/**'

# Add 'pkg2' label to any change to pkg2 package.
pkg2:
- all:
  - changed-files:
    - any-glob-to-any-file: 'pkg2/**'

# Add 'pkg3' label to any change to pkg3 package.
pkg3:
- all:
  - changed-files:
    - any-glob-to-any-file: 'pkg3/**'

# Add 'feature' label to any PR where the head branch name starts with `feature/feat` or has a `feature/feat` section in the name
feature:
 - head-branch: ['^feature', 'feature', '^feat', 'feat']

# Add 'bug' label to any PR where the head branch name starts with `fix/bug` or has a `fix/bug` section in the name
bug:
 - head-branch: ['^bug', 'bug', '^fix', 'fix']
